services:
  postgres:
    image: postgres:15
    container_name: iot_postgres_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpassword
      POSTGRES_DB: iotdb
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iot_rabbitmq_dev
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: iot_backend_dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PORT: 3000
      DATABASE_URL: postgres://iotuser:iotpassword@postgres:5432/iotdb
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      NODE_ENV: development
      DEVICE_API_KEY: ${DEVICE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./:/app
      - /app/node_modules

    live_feed:
      build:
        context: ./src/microservices/live_feed
        dockerfile: DockerfilePy
      container_name: iot_live_feed
      restart: always
      ports:
        - "5000:5000"
      environment:
        FLASK_ENV: production

volumes:
  pgdata_dev:
