

services:
  postgres:
    image: postgres:15
    container_name: iot_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpassword
      POSTGRES_DB: iotdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iot_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  backend:
    build: .
    container_name: iot_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 3000
      DATABASE_URL: postgres://iotuser:iotpassword@postgres:5432/iotdb
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      DEVICE_API_KEY: ${DEVICE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    command: npm run start:watch

volumes:
  pgdata:
